kind: Service
apiVersion: v1
metadata:
  name: ${{ values.component_id }}
spec:
  ports:
    - name: http-8081
      port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: ${{ values.component_id }}