apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: software-templates
  description: A collection of Backstage templates for Janus-IDP
spec:
  type: url
  targets:
    - https://github.com/PatAKnight/template/blob/main/python-github-actions-argocd-template/template.yaml
    - https://github.com/PatAKnight/template/blob/main/python-golden-path-template/template.yaml
    - https://github.com/janus-idp/software-templates/blob/main/scaffolder-templates/quarkus-web-template/template.yaml