kind: Deployment
apiVersion: apps/v1
metadata:
  name: ${{ values.component_id }}
  labels:
    backstage.io/kubernetes-id: ${{values.component_id | dump}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${{ values.component_id }}
  template:
    metadata:
      labels:
        app: ${{ values.component_id }}
        backstage.io/kubernetes-id: ${{values.component_id | dump}}
    spec:
      containers:
        - name: ${{ values.component_id }}
          image: quay.io/${{ values.imagenamespace }}/${{ values.component_id }}:latest
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"