apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: ${{ values.component_id }}-pipeline-run-init
  namespace: ${{ values.namespace }}
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
  labels:
    tekton.dev/pipeline: ${{ values.component_id }}-pipeline
    type: pipeline
spec:
  params:
    - name: source-repo
      value: 'https://github.com/${{ values.org }}/${{ values.component_id }}.git'
    - name: source-branch
      value: ${{ values.defaultBranch }}
    - name: output-image
      value: quay.io/${{ values.imagenamespace }}/${{ values.component_id}}
  pipelineRef:
    name: ${{ values.component_id }}-pipeline
  serviceAccountName: pipeline
  workspaces:
    - name: source-folder
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
